config/routes.rb
GitReal::Application.routes.draw do
  get 'auth',             to: 'users#auth'
  get 'oauth/github',     to: 'users#handle_auth'
  get 'login',            to: 'users#login'
  get 'logout',           to: 'users#logout'

  # Repos
  get 'repos/:repo_name', to: 'homepage#repos', as: 'repo_show'

  root to: 'homepage#index'
end

app/models/github_profile.rb
class GithubProfile < ActiveRecord::Base
  validates :handle, :oauth_token, presence: true
  validates :handle, uniqueness: true
end

app/controllers/application_controller.rb
require 'githubber'

class ApplicationController < ActionController::Base
  include ActionView::Helpers::OutputSafetyHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Context
  include UserSession

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ALERT_TYPES = [:success, :info, :warning, :danger]

  helper_method :bootstrap_flash
  helper_method :is_logged_in?
  helper_method :current_user_profile

  private

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                            content_tag(:button, raw("&times;"), 
                                       :class => "close", 
                                       "data-dismiss" => "alert",
                                       "aria-hidden" => "true",
                                       "type" => "button") +
                            msg,
                           :class => "alert fade in alert-#{type} alert-dismissable")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def current_github_user
    @current_github_user ||= Githubber::User.new(current_user_profile.oauth_token)
  end
end

app/controllers/homepage_controller.rb
require 'user_session'

class HomepageController < ApplicationController
  include UserSession
  before_filter :prompt_for_auth

  def index
    @repos = current_github_user.repos
  end

  def repos
    @repo_name = params[:repo_name]
    @my_handle = current_github_user.handle
    @stats = current_github_user.stats(@my_handle, @repo_name)
  end
end

app/controllers/users_controller.rb
require 'githubber'
require 'user_session'

class UsersController < ApplicationController
  include UserSession

  def auth
    redirect_to Githubber::User.auth_redirect_url
  end

  def handle_auth
    oauth_token = user_oauth_token
    unless oauth_token
      flash[:error] = "Unable to login via Github"
      redirect_to login_path and return
    end

    initiate_session(oauth_token)
    flash[:success] = "You have successfully logged in"
    redirect_to '/'
  end

  def login
  end

  def logout
    clear_session

    flash[:info] = "You have been logged out"
    redirect_to login_path
  end

  private

  def user_oauth_token
    github_auth_code ? Githubber::User.oauth_token(github_auth_code) : nil
  end

  def github_auth_code
    params[:code]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
You are now logged in, <%= current_user_profile.name %>

<br />

<table class="table">
  <% @repos.each do |repo| %>
    <tr>
      <td>
        <a href="<%= repo_show_path(repo.name) %>">
        <%= repo.name %>
      </td>
    </tr>
  <% end %>
</table>

app/views/homepage/repos.html.erb
<h2> <%= @repo_name %> </h2>

<hr />

<h3>Number of Pull Requests By User</h3>
<table class="table">
  <tr>
    <th>
      Handle
    </th>
    <th>
      Numer of PRs
    </th>
    <th>
      % of total
    </th>
  </tr>
  <% @stats[:number_of_prs_by_user].each do |user, num| %>
    <tr>
      <td>
        <%= user %>
      </td>
      <td>
        <%= num %>
      </td>
      <td>
        <%= num.to_f / @stats[:total_prs] %>
      </td>
    </td>
  <% end %>
</table>

<hr />

<h3>Commenters</h3>
<table class="table">
  <tr>
    <th>
      Handle
    </th>
    <th>
      Num PRs commented on
    </th>
    <th>
      Total Comments
    </th>
    <th>
      Avg Comments per PR
    </th>
    <th>
      % of your PRs they commented
    </th>
    <th>
      % of their PRs you commented on
    </th>
  </tr>
  <% if @stats[:unique_commenters_by_user][@my_handle] %>
    <% @stats[:unique_commenters_by_user][@my_handle].each do |handle, num_comments| %>
      <tr>
        <td>
          <%= handle %>
        </td>
        <td>
          <%= num_comments %>
        </td>
        <td>
          <%= @stats[:comments_for_user][@my_handle][handle] %>
        </td>
        <td>
          <%= @stats[:comments_for_user][@my_handle][handle].to_f / num_comments %>
        </td>
        <td>
          <%= (num_comments * 100.00) / @stats[:number_of_prs_by_user][@my_handle] %>
        </td>
        <td>
          <% if @stats[:unique_commenters_by_user][handle] && @stats[:number_of_prs_by_user][handle] %>
            <%= (@stats[:unique_commenters_by_user][handle][@my_handle].to_f * 100.00) / @stats[:number_of_prs_by_user][handle] %>
          <% else %>
            0
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<hr />

<h3>Mentions</h3>
<table class="table">
  <tr>
  	<th>
      Handle
    </th>
    <th>
      Num of mentions
    </th>
	<th>
      Num of times they pinged you
    </th>
    <th>
      Num of times you pinged them
    </th>
  </tr>
  <% if @stats[:unique_commenters_by_user][@my_handle] %>
    <% @stats[:unique_commenters_by_user][@my_handle].each do |handle, num_comments| %>
      <tr>
      	<td>
          <%= handle %>
        </td>
        <td>
          <% if @stats[:number_of_mentions][handle] %>
            <%= @stats[:number_of_mentions][handle] %>
          <% else %>
            0
          <% end %>
        </td>
        <td>
          <% if @stats[:mentions_by_user][handle] && @stats[:mentions_by_user][handle][@my_handle] %>
            <%= @stats[:mentions_by_user][handle][@my_handle] %>
          <% else %>
            0
          <% end %>
        </td>
        <td>
          <% if @stats[:mentions_by_user][@my_handle] && @stats[:mentions_by_user][@my_handle][handle] %>
            <%= @stats[:mentions_by_user][@my_handle][handle] %>
          <% else %>
            0
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Git Real" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Git Real</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse navbar-right">
          <ul class="nav navbar-nav">
            <% if is_logged_in? %>
              <li><%= link_to "Logout", logout_path  %></li>
            <% else %>
              <li><%= link_to "Login", login_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
        </div>
      </div><!--/row-->

      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <hr />
        <p>&copy; Tapjoy 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/login.html.erb
<p class="text-center">
  <a class="btn btn-social btn-github" href="<%= auth_path %>">
      <i class="fa fa-github"></i> Sign in with Github
  </a>
</p>